baseURL = "https://master.d2uw4n28hq77cy.amplifyapp.com"
languageCode = "en-us"
title = "SPIC'N SPAN"
theme = "kross-hugo"
summaryLength = "10"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"


  
# navigation
[menu]
    
  
 
[params]
logo = ""
home = ""
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  [params.contact]
  enable = false
  formAction = "#" #contact form works with formspree.io

  [params.footer]
  email = "steve.fruits@email.com"
  phone = "+880 2544 658 256"
  address = "125/A, CA Commercial Area, California, USA"